### PR TITLE
Add python3-pip as build dependency

### PR DESCRIPTION
**Pull request by rcrdnalor**
Commit https://github.com/MythTV/mythtv/commit/8ece26b added python3-pip as build dependency (in configure) for modern Linux variants.

Updated specs for Ubuntu >= 23.04, Debian 12 and Fedora 39+.

 - MythTV master for Ubuntu 23.04 is already build with python3-pip on Launchpad.
 - Debian 12 has a recent version of python3-pip.
 - Fedora 39, once released has python3.12 which requires python3-pip for building.

Note: For Debian and its derivatives, the package python3-pip depends on python3-wheel.

Completely untested.

### CODE REVIEW

**Comment by rcrdnalor** [comment]
@billmeek : Could you please review it ?

**Comment by billmeek** [comment]
Will do when I get back. Probably next week.

**Comment by kmdewaal** [comment]
Updating ansible with PR36 and then executing gives this:
```
klaas@kasus:~/git/ansible$ ./mythtv.yml --limit=localhost
[DEPRECATION WARNING]: [defaults]collections_paths option, does not fit var naming standard, use the singular form collections_path instead. This feature will be removed from ansible-core in version 2.19. Deprecation warnings
 can be disabled by setting deprecation_warnings=False in ansible.cfg.

```

**Comment by kmdewaal** [comment]
Hi Roland, from your comment on issue #848
```
On Ubuntu, you need only install the python3-pip package.
On Fedora 39, you need to install the python3-wheel package as well.
```
Tested this also yesterday on Fedora 39 but I the python3-wheel was not installed by ansible. 
Does it still need to be added or did I miss something?

**Pull request merged**
