### PR TITLE
Update CI versions

### PR DESCRIPTION
**Pull request by garybuhrmaster**
Update the various Fedora and Ubuntu build versions to the current upstream supported versions.

### CODE REVIEW

**Comment by garybuhrmaster** [comment]
It appears github had an internal issue for one of the actions jobs resulting in a checkout timeout.  Someone with appropriate privs in the repo should be able to rerun that failed job to achieve check success if that is a decision point.

**Comment by billmeek** [comment]
@garybuhrmaster, Re-ran, reported SUCCESS, but then I got an email with a failure for Fedora 41:

`Failed to download metadata (metalink: "https://mirrors.fedoraproject.org/metalink?repo=fedora-41&arch=x86_64") for repository "fedora"`

FYI only, I did rebase the PR because f3bd3ec was missing.

**Comment by garybuhrmaster** [comment]
It looks like github's internal failures (for which they revered some set of DB changes) has result in recent comments being "disappeared".  In any case to respond to your (now disappeared) comment:

> `Failed to download metadata (metalink: "https://mirrors.fedoraproject.org/metalink?repo=fedora-41&arch=x86_64") for repository "fedora"`

It appears there was a glitch in the source.  The Fedora mirrors metalink reference was failing.  It now seems to be resolving and returning a (shortened) list of repo locations for me.  As the Fedora mirror sites get updated things will likely return to normal.  As the mirror(s) are distributed, github might get lucky or unlucky as to which mirrorlist site it is pointed to, but you could try to rerun the failed job (now, or tomorrow) to see if it still fails.  I would

**Comment by billmeek** [comment]
Re-ran A-OK. I'm guilty of deleting the comment. Thought I had time to look into the failure but ran out of it. Thanks for the mirror comments.

**Comment by garybuhrmaster** [comment]
> Re-ran A-OK. I'm guilty of deleting the comment.

I was not (fully) aware that github allows one to revise history by deleting it (rather that showing the modification history).  That seems, well, really bad (allowing one to disappear facts and the history, entirely (that is what authoritarian regimes do)), but so be it.  Thanks for the clarification.

**Pull request merged**
